name: CI/CD Pipeline Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Setup Git identity
        run: |
          git config --global user.email "alexoursel6@gmail.com"
          git config --global user.name "Oursel06"

      - name: Deploy to gh-pages branch
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REACT_APP_API_URL_USER: ${{ secrets.REACT_APP_API_URL_USER }}
          REACT_APP_API_URL_POST: ${{ secrets.REACT_APP_API_URL_POST }}
        run: npm run deploy
